### ISSUE TITLE
Stuck in package picker submenu

### ISSUE THREAD

**Issue by wiredmatt** [flame-engine/ignite-cli#12]
![image](https://github.com/flame-engine/ignite-cli/assets/29718978/5b8aa957-b5bd-48e1-95d4-6057a154fd15)

Windows 11, Powershell.

Can only select or deselect the first option with space, but nothing more with arrow keys or Enter

**Comment by system32uwu** [comment]
`ignite create --name=dino_game --org=org.system32uwu.games --create-folder=true --flame-version=1.8.0 --extra-packages="flame_audio"` this also fails with this message:

```
Unhandled exception:
type 'String' is not a subtype of type 'List<String>?' in type cast
#0      getMultiOption (package:ignite_cli/utils.dart:86:29)
#1      createCommand (package:ignite_cli/commands/create_command.dart:54:25)
#2      mainCommand (package:ignite_cli/main.dart:73:11)
<asynchronous suspension>
```

**Comment by ufrshubham** [comment]
Same problem is observed when using cmd and git-bash as well

**Comment by BrunoJay** [comment]
same here

**Comment by luanpotter** [comment]
So the issue here is two-fold:

1. the `prompts` library "advanced" prompt selectors seems to have some issue with rendering / working in some terminals; probably the same issue as https://github.com/flame-engine/ignite-cli/issues/14 and can be tracked there.

2. there is currently no way to manually specify the options via flags because of the parsing bug. that I have solved here https://github.com/flame-engine/ignite-cli/pull/16
