### ISSUE TITLE
Ignite create using the 'Example template' results in 'Invalid template example'

### ISSUE THREAD

**Issue by Jan-Stepien** [flame-engine/ignite-cli#9]
When creating choosing Example template unhandled exceptions appears

```
➜  one_bit ignite create
✔ Choose a name for your project:  ‥ my_game
✔ Choose an org for your project:  ‥ org.my_game.game

Your current directory is: /Users/janstepien/projects/one_bit
Do you want to put your project files directly on the current dir or do you want to create a folder called my_game?:

* Create a folder called my_game
Put the files directly on /Users/janstepien/projects/one_bit  

What template would you like to use for your new project?:

Simple: an empty Flame project with just the bare minimums to get you up and running.  
* Example: a very simple example game built on top of Simple; give you some ideas of how to use Flame if you are new.

Running flutter create on /Users/janstepien/projects/one_bit/my_game ...
$ flutter create --org org.my_game.game --project-name my_game .
Signing iOS app for device deployment using developer identity: "Apple Development: <removed>"
Recreating project ....
  test/widget_test.dart (created)
  android/app/src/main/kotlin/org/my_game/game/my_game/MainActivity.kt (created)
Running "flutter pub get" in my_game...                          2,439ms
Wrote 5 files.

All done!
In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart.

Unhandled exception:
Invalid template example
#0      getTemplateForName (package:ignite_cli/templates/template.dart:54:5)
#1      createCommand (package:ignite_cli/commands/create_command.dart:82:9)
<asynchronous suspension>
#2      mainCommand (package:ignite_cli/main.dart:65:5)
<asynchronous suspension>

```

**Comment by spydon** [comment]
Hi, which version of Ignite do you have?

**Comment by Jan-Stepien** [comment]
Tricky question since `ignite -v` fails #8 
But `flutter pub global activate ignite_cli` proves:
Package ignite_cli is currently active at version 0.4.0.

**Comment by spydon** [comment]
Try 0.5.0-rc.1 instead, I think that you have to set that version explicitly when activating it from pub.

**Comment by spydon** [comment]
0.5.0 is also released now which should solve this.
